from typing import Any, Dict, Optional, Iterable, Union

_InfoDict = Dict[str, Any]

class YoutubeDL:
    def __init__(self, params: Any = ...) -> None: ...
    def extract_info(self, url: str, download: bool = ...) -> _InfoDict: ...
    def prepare_filename(self, info_dict: _InfoDict) -> str: ...
    def __enter__(self) -> "YoutubeDL": ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
